debug: false
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yunshu?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&serverTimezone=UTC
    username: root
    password: kingston
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
